############################## REPO DE DATOS ###################################
spring.datasource.url=jdbc:sqlserver://;serverName=localhost;databaseName=bartolito
spring.datasource.username=sa
spring.datasource.password=admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
server.servlet.context-path=/bauth