############################## REPO DE DATOS BD LOLFAR ###################################
spring.datasource.url=jdbc:sqlserver://;serverName=localhost;databaseName=bartolito
spring.datasource.username=sa
spring.datasource.password=admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


############################## REPO DE DATOS BD SIGOLDB ###################################
spring.second-datasource.url=jdbc:sqlserver://localhost;databaseName=bartolito_sigoldb
spring.second-datasource.username=sa
spring.second-datasource.password=admin
spring.second-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
server.servlet.context-path=/catamedi

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB